# -*- coding: utf-8 -*-
"""aula03_2020_08_27_sigmoid.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12pijc-ZRg4AYCeHZVLKXpoTTXyonOtfg
"""

import math
import time

"""## SIGMOID"""

start = time.time()

matrix_input = [[0, 0], [0, 1], [1, 0], [1, 1]]

w1 = 7.0
w2 = 2.0
w3 = 9.0
w4 = 4.0
w5 = 5.0
w6 = 1.0

t1, t2, t3 = 8.0, 3.0, 5.5

print(f'l1\tl2\ts1\to1\ts2\to2\ts3\to3')
print(63 * '-')

for l1, l2 in matrix_input:
    s1 = l1 * w1 + l2 * w2
    o1 = 1.0 / (1.0 + math.exp(10.0 * (s1 - t1)))

    s2 = l1 * w3 + l2 * w4
    o2 = 1.0 / (1.0 + math.exp((- 10.0) * (s2 - t2)))

    s3 = o1 * w5 + o2 * w6
    o3 = 1.0 / (1.0 + math.exp((- 10.0) * (s3 - t3)))
    print(f'{l1}\t{l2}\t{s1:.0f}\t{o1:.0f}\t{s2:.0f}\t{o2:.0f}\t{s3:.0f}\t{o3:.5f}')

end = time.time()

runtime = end - start
print(f'\nRuntime: {runtime:.10f} seconds')

# OUTPUT
# l1  l2  s1  o1  s2  o2  s3  o3
# -----------------------------------
# 0   0   0   1   0   0   5   0.00669
# 0   1   2   1   4   1   6   0.99330
# 1   0   7   1   9   1   6   0.99329
# 1   1   9   0   13  1   1   0.00000
# 
# Runtime: 0.0005943775 seconds