# -*- coding: utf-8 -*-
"""aula02_2020_08_26_perceptron.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ms4NLnlcQ_JZthO6umUNlHbvu099EoGs
"""

import math

"""# Perceptron

## AND
"""

matrix_input = [[0, 0], [0, 1], [1, 0], [1, 1]]

w1, w2, t = 3,  5,  6

print(f'l1\tl2\ts\to1')
print(26 * '-')
for l1, l2 in matrix_input:
    s = l1 * w1 + l2 * w2
    o1 = 1 if (s > t) else 0
    print(f'{l1}\t{l2}\t{s}\t{o1}')

# OUTPUT
# l1  l2  s   o1
# --------------
# 0   0   0   0
# 0   1   5   0
# 1   0   3   0
# 1   1   8   1

"""## OR"""

matrix_input = [[0, 0], [0, 1], [1, 0], [1, 1]]

w1, w2, t = 8, 5, 4

print(f'l1\tl2\ts\to1')
print(26 * '-')
for l1, l2 in matrix_input:
    s = l1 * w1 + l2 * w2
    o1 = 0 if (s < t) else 1
    print(f'{l1}\t{l2}\t{s}\t{o1}')

# OUTPUT
# l1  l2  s   o1
# ---------------
# 0   0   0   0
# 0   1   5   1
# 1   0   8   1
# 1   1   13  1

"""# Multiperceptron

## XOR
"""

matrix_input = [[0, 0], [0, 1], [1, 0], [1, 1]]

w1 = 7
w2 = 2
w3 = 9
w4 = 4
w5 = 5
w6 = 1

t1, t2, t3 = 8, 3, 5.5

print(f'l1\tl2\ts1\to1\ts2\to2\ts3\to3')
print(58 * '-')
for l1, l2 in matrix_input:
    s1 = l1 * w1 + l2 * w2
    o1 = 1 if (s1 < t1) else 0

    s2 = l1 * w3 + l2 * w4
    o2 = 1 if (s2 > t2) else 0

    s3 = o1 * w5 + o2 * w6
    o3 = 1 if (s3 > t3) else 0
    print(f'{l1}\t{l2}\t{s1}\t{o1}\t{s2}\t{o2}\t{s3}\t{o3}')

# OUTPUT
# l1  l2  s1  o1  s2  o2  s3  o3
# ------------------------------
# 0   0   0   1   0   0   5   0
# 0   1   2   1   4   1   6   1
# 1   0   7   1   9   1   6   1
# 1   1   9   0   13  1   1   0